### ISSUE TITLE
Improved method of reporting harmful content

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#3272]
### User story
Users should be able to see at the bottom of the record page the three different form options to ask a question, suggest a correction and report harmful language content. Align with the feedback/reporting mechanisms in Pulfalight to make a more consistent experience for users across our discovery systems.

### Concrete example
- https://findingaids.princeton.edu/catalog/C0101
- https://github.com/pulibrary/orangelight/issues/3274#issuecomment-1354801937

### Implementation notes, if any
- At any time when the user scrolls up or down keep the feedback form bar at the bottom of the browser window so that it is always visible. 

- For the individual form please review the wireframe in the proposal for this feature https://docs.google.com/document/d/1HPOUhTo6T9Zi57G0z-hsKIJCKU1u3k_KZgyJyuHunJw/edit

- Catalog feedback for harmful content will be sent to a new queue. Esme will ask SC for - the new queue. Message is only 'required' in the current feedback.

- Proposal received and approved by DSSG: https://docs.google.com/document/d/1HPOUhTo6T9Zi57G0z-hsKIJCKU1u3k_KZgyJyuHunJw/edit

**Comment by christinach** [comment]
- Align feedback/reporting mechanisms with Pulfalight
- Catalog feedback for harmful content will be sent to a new queue. Esme will ask SC for - the new queue. Message is only required in the current feedback. 
- Create a wireframe in orangelight of the three feedback options that we currently have in pulfalight.

**Comment by kevinreiss** [comment]
- [ ] Add the new feedback bar to the "show page"
- [ ] Create the Ask A Question - emails to reference queue
- [ ] Create Suggest a Correction Form - emails to cataloging queue
- [ ] Create the Report Harmful Language Form - email to new harmful content queue.

**Comment by christinach** [comment]
done!
