### ISSUE TITLE
Include EZProxy link in the search result json

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3458]
### User story

As a user of discovery utils, I want any Princeton subscription resources to include an EZProxy prefix so I can authenticate into them using CAS.

### Acceptance criteria

- [ ] The value of the `electronic_access_1display` in https://catalog.princeton.edu/catalog.json?search_field=all_fields&q=query has the EZProxy prefix if it matches this list: https://github.com/pulibrary/orangelight/blob/main/config/hosts.dat
- [ ] https://catalog.princeton.edu/catalog.json?search_field=all_fields&q=query is otherwise the same as it was before

### Implementation plan

- [ ] Address #3488 
- [ ] Convert the format index field helper method into a view component (otherwise, the icon will be included in the json output) See #3459
- [ ] Convert the current JSON field handling from https://github.com/pulibrary/orangelight/blob/main/app/views/catalog/_field.json.jbuilder into a step in the rendering pipeline
- [ ] Remove our override of https://github.com/pulibrary/orangelight/blob/main/app/views/catalog/_field.json.jbuilder
- [ ] Add a step in the rendering pipeline that converts the URL using the logic added in #3433

**Comment by kevinreiss** [comment]
The E-resource group says the clean-up is moving more rapidly than expected. Will check back in on this on 3/29 and e-resource check-in.

**Comment by kevinreiss** [comment]
The data is now in state that supersedes the need to implement this ticket. Closing.
