### ISSUE TITLE
[Search results] Implement Search Term Highlighting on Search Results Display

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3793]
- [x] https://github.com/pulibrary/orangelight/issues/3829
- [x] https://github.com/pulibrary/orangelight/issues/3803
- [x] https://github.com/pulibrary/orangelight/issues/3797
- [x] https://github.com/pulibrary/orangelight/issues/3830
- [x] https://github.com/pulibrary/orangelight/issues/3825
- [x] https://github.com/pulibrary/orangelight/issues/3796
- [x] https://github.com/pulibrary/orangelight/issues/3795
- [x] https://github.com/pulibrary/orangelight/issues/3794
- [x] https://github.com/pulibrary/orangelight/issues/3763
